# Chapter 11: Pandas (continued) `Dataframes`

A `DataFrame` is a 2-dimensional labeled data structure with columns of potentially different types. One way to think about a `Dataframe` is as a two-dimensional list of data, where both rows and columns are structured, like a spreadsheet, or a `dict` of `Series`.
You can create a `DataFrame` from a list or dict of Series, a 2 axes ndarray

In [9]:
import pandas as pd
import numpy as np

### Resume where we stopped in 11-1

In [33]:
grades  = np.loadtxt('grades.csv',delimiter = ',', skiprows= 1, usecols=(3, 4, 5, 6, 7, 8, 9), max_rows=10)
keys = ("Quizzes_average", "HW1_mark", "HW2_mark", "HW3_mark", "Exam1_mark", "Exam2_mark", "Final_exam_mark")

gradesD = {}
for col, k in enumerate(keys):
    gradesD[k] = grades[:,col]

gradesL = []
for row in grades:
    record = {}
    for col, k in enumerate(keys):
        record[k] = row[col]
    gradesL.append(record)

rowD0 = pd.Series(gradesL[0])
rowD1 = pd.Series(gradesL[1])
rowD0.name = '620565656'
rowD1.name = '107856531'

In [34]:
gradesDF = pd.DataFrame([rowD0, rowD1])
gradesDF

,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark
620565656,96.0,77.0,82.0,91.0,88.0,78.0,91.0
107856531,94.0,76.0,87.0,90.0,90.0,67.0,88.0

In [37]:
print(gradesDF['HW1_mark'])
print(gradesDF.loc['620565656'])
print(type(gradesDF['HW1_mark']))
print(type(gradesDF.loc['620565656']))

620565656    77.0
107856531    76.0
Name: HW1_mark, dtype: float64
Quizzes_average    96.0
HW1_mark           77.0
HW2_mark           82.0
HW3_mark           91.0
Exam1_mark         88.0
Exam2_mark         78.0
Final_exam_mark    91.0
Name: 620565656, dtype: float64
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

A convenient shortcut: if the column names are valid python names (no spaces etc), it is possible to access columns directly using the "." operator:

In [38]:
print(gradesDF['HW1_mark'])
print(gradesDF.HW1_mark)

620565656    77.0
107856531    76.0
Name: HW1_mark, dtype: float64
620565656    77.0
107856531    76.0
Name: HW1_mark, dtype: float64

Before we continue, let's generate a larger dataFrame by reading the entire grades file

In [32]:
gradesDF2 = pd.read_csv("grades.csv", skipinitialspace=True, index_col=2)
gradesDF2.head() # same as gradesDF2[:5]

,First_name,Last_name,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark
Student_number,,,,,,,,,
620565656,BARRY,LAMB,96,77,82,91,88,78,91
107856531,NARIMAN,PELUCHONDELAGARZA,94,76,87,90,90,67,88
7943944,VITALY,KHAN,92,79,85,92,76,60,87
114037001,NATALYA,SUTRADHAR,90,75,78,88,90,67,84
581943811,MAGARET,HIRJI,88,76,91,98,96,56,81

We now have the best of a list of dictionaries and a dictionary of lists:

In [39]:
print(type(gradesDF2['HW3_mark']))
print(type(gradesDF2.loc[7943944]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [ ]:
# selecting rows:

# loc is label-based, iloc is index-based
print(gradesDF2.loc[114037001])
print(gradesDF2.iloc[2])

# First name         NATALYA
Last name          SUTRADHAR
Quizzes average           90
HW1 mark                  75
HW2 mark                  78
HW3 mark                  88
Exam1 mark                90
Exam2 mark                67
Final exam mark           84
Name: 114037001, dtype: object
# First name       VITALY
Last name            KHAN
Quizzes average        92
HW1 mark               79
HW2 mark               85
HW3 mark               92
Exam1 mark             76
Exam2 mark             60
Final exam mark        87
Name: 7943944, dtype: object

In [ ]:
# selecting columns
print(gradesDF2.HW1_mark[:10])
# or equivalently gradesDF2['HW1_mark'][:10]

Student_number
620565656    77
107856531    76
7943944      79
114037001    75
581943811    76
367541502    70
602646616    81
282046779    75
961460380    75
527925346    70
Name: HW1_mark, dtype: int64
75.01195219123505

In [57]:
# Computing the HW1 average: 
print(gradesDF2.HW1_mark.mean())

75.01195219123505

In [42]:
# Operation on columns
gradesDF2['HW_avg'] = (gradesDF2['HW1_mark'] + gradesDF2['HW2_mark'] + gradesDF2['HW3_mark']) / 3
gradesDF2.head()

,First_name,Last_name,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark,HW_avg
Student_number,,,,,,,,,,
620565656,BARRY,LAMB,96,77,82,91,88,78,91,83.333333
107856531,NARIMAN,PELUCHONDELAGARZA,94,76,87,90,90,67,88,84.333333
7943944,VITALY,KHAN,92,79,85,92,76,60,87,85.333333
114037001,NATALYA,SUTRADHAR,90,75,78,88,90,67,84,80.333333
581943811,MAGARET,HIRJI,88,76,91,98,96,56,81,88.333333

## 11.3 Sorting

In [44]:
gradesDF2.sort_values('HW_avg', ascending=False).head()

,First_name,Last_name,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark,HW_avg
Student_number,,,,,,,,,,
441797054,ZHONG,TUNCAY,100,87,93,91,87,74,90,90.333333
882363866,KOHL,SU,94,82,98,91,91,74,90,90.333333
463318745,BROOKLYN,SCOTT,98,83,94,91,91,66,90,89.333333
586057811,LORI-ANN,VANOIRSCHOT,92,84,86,98,91,64,82,89.333333
128992445,MARITZA,YIN,93,82,98,87,90,64,97,89.000000

## 11.4 Selecting / filtering

### Selecting columns:

In [45]:
gradesDF2[['HW1_mark', 'HW2_mark', 'HW3_mark']]

                HW1_mark  HW2_mark  HW3_mark
Student_number
620565656             77        82        91
107856531             76        87        90
7943944               79        85        92
114037001             75        78        88
581943811             76        91        98
...                  ...       ...       ...
248015969             72        82        91
970187185             72        88        94
300391145             73        84        94
149614639             78        79        91
849296811             65        86        87

[251 rows x 3 columns]

In [55]:
# We could also have computed the grades average using:
gradesDF2[ ['HW1_mark', 'HW2_mark', 'HW3_mark']].mean(axis=1)

Student_number
620565656    83.333333
107856531    84.333333
7943944      85.333333
114037001    80.333333
581943811    88.333333
               ...
248015969    81.666667
970187185    84.666667
300391145    83.666667
149614639    82.666667
849296811    79.333333
Length: 251, dtype: float64

In [58]:
# and the average for these items using
gradesDF2[ ['HW1_mark', 'HW2_mark', 'HW3_mark']].mean(axis=0)

HW1_mark    75.011952
HW2_mark    84.737052
HW3_mark    89.486056
dtype: float64

### Selecting rows:

In [54]:
A = gradesDF2['HW_avg'] >= 90
gradesDF2[A]

,First_name,Last_name,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark,HW_avg,HW_avg2
Student_number,,,,,,,,,,,
882363866,KOHL,SU,94,82,98,91,91,74,90,90.333333,90.333333
441797054,ZHONG,TUNCAY,100,87,93,91,87,74,90,90.333333,90.333333

In [59]:
B = (gradesDF2['HW_avg'] >= 85) & (gradesDF2['HW_avg'] < 90)
gradesDF2[B]

,First_name,Last_name,Quizzes_average,HW1_mark,HW2_mark,HW3_mark,Exam1_mark,Exam2_mark,Final_exam_mark,HW_avg,HW_avg2
Student_number,,,,,,,,,,,
7943944,VITALY,KHAN,92,79,85,92,76,60,87,85.333333,85.333333
581943811,MAGARET,HIRJI,88,76,91,98,96,56,81,88.333333,88.333333
602646616,ERICKA,HOU,93,81,90,86,90,76,92,85.666667,85.666667
282046779,ABDOOL,VILLASPIN,87,75,90,90,85,70,89,85.000000,85.000000
961460380,FERN,HUANG,100,75,91,91,97,53,91,85.666667,85.666667
...,...,...,...,...,...,...,...,...,...,...,...
894355623,ANKUSH,GRAHAM,97,76,83,99,92,76,81,86.000000,86.000000
485307898,SUKHPREET,PASPALOFSKI,93,78,90,89,80,69,91,85.666667,85.666667
764383512,DAMIEN,JEGAJEEVAN,92,69,95,94,81,65,76,86.000000,86.000000
51612076,INDIA,VANROOYEN,90,83,89,92,75,65,89,88.000000,88.000000
226246762,ANTONINA,VECCHIO,90,76,93,93,83,62,93,87.333333,87.333333

In [ ]:
# Another way using a 'query'. Note the back quotes `
B2 = gradesDF2.query("80 <= `HW_avg` < 90")

Save the full data to excel:

In [63]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [64]:
gradesDF2.to_excel('grades.xlsx')