In [1]:
import numpy as np
import pandas as pd

# Monday March 16th 2026

## Introduction to Pandas

![Panda Picture](panda.jpg)

- We have seen how Numpy arrays are great tools for working with data of a uniform type.
    - In Pythonic words, we say Numpy arrays are homogeneous containers.
    - This allows Numpy arrays to have a single type - called their dtype.

In [2]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1.,2.,3.],[4.,5,6]])
print(f"A = {A}")
print(f"B = {B}")

A = [[1 2 3]
 [4 5 6]]
B = [[1. 2. 3.]
 [4. 5. 6.]]

In [3]:
print(f"A has dtype : {A.dtype}")
print(f"B has dtype : {B.dtype}")

A has dtype : int64
B has dtype : float64

Having a homogeneous type has many advantages (there are three key ones lets try to name them here!)

- Vectorization
- Only have to compare/cast types once
- Nice memory model

However, we are oftentimes faced with data that is not homogeneous. In these cases, it would be nice to have a library with some of the similar functionality as Numpy i.e. **vectorization** and **columnization**, without the constraint of homogeneity. 

Such a library is **Pandas**.

### Pandas

Just as Numpy offers us the new data type of Numpy nd-arrays, Pandas comes with two new data types called **series** and **data frames**.

![Panda picture](KungFuPanda.png)

### Series

A **series** is a one-dimensional labeled array.

In [4]:
a = [1, 7, 2]
ser1 = pd.Series(data = a)

print(ser1)

0    1
1    7
2    2
dtype: int64

In [5]:
print(ser1[2])

2

In [6]:
ser2 = pd.Series(data = a, index = ["x", "y", "z"])
print(ser2)

x    1
y    7
z    2
dtype: int64

In [7]:
d = {"a" : 1, "b" : 2, "c" : 3}
ser = pd.Series(data = d, index = ["a","b","c"])
print(ser)

a    1
b    2
c    3
dtype: int64

### Labels are helpful 

Suppose we have two datasets. They have some common data points, but they do not overlap completely. How can we make sure that arithmetic operations on them are well defined?

In [8]:
hw1_data = {'John' : 72.0, 'Nathan' : 100.0, 'Matthew' : 88.9}
hw2_data = {'Nathan' : 100.0, 'Matthew' : 93.9}

hw1 = pd.Series(data = hw1_data)
hw2 = pd.Series(data = hw2_data)

In [9]:
hw_avg = (hw1 + hw2)/2

hw_avg

John         NaN
Matthew     91.4
Nathan     100.0
dtype: float64

**Notice:** The same task would a lot more work with Numpy arrays.

**However** this brings up an interesting point. Oftentimes our data will be incomplete. Pandas deals with incomplete data by labelling it with *NaN* standing for *Not a Number*. Dealing with missing data is one of the most important topics in data science (falling into the larger category of data sanitization). We will discuss how Pandas can help us deal with *NaN* values shortly.

### Converting series back to other types

Pandas series can be converted to many other Python container types.

In [10]:
l_ser = ser.to_list()
print(l_ser)
d_ser = ser.to_dict()
print(d_ser)
np_ser = ser.to_numpy()
print(np_ser)

[1, 2, 3]
{'a': 1, 'b': 2, 'c': 3}
[1 2 3]

### Names

Pandas series also have a `name` attribute. This will become useful when creating `DataFrames` from Series.

In [11]:
ser.name = 'My Series'

In [12]:
ser

a    1
b    2
c    3
Name: My Series, dtype: int64

### DataFrames

A **DataFrame** is a two-dimensional labeled data structure that consists of columns and rows. A DataFrame represents a spreadsheet-like data structure where each column is a **Series**.

In [13]:
data = {
    "Name" : ["John", "Nathan", "Lily", "Corrin"],
    "Age" : [26,27,19,26],
    "City" : ["Hamilton", "Dundas", "Halifax", "Charlottetown"]
}

df = pd.DataFrame(data)

df

     Name  Age           City
0    John   26       Hamilton
1  Nathan   27         Dundas
2    Lily   19        Halifax
3  Corrin   26  Charlottetown

In [14]:
data = [
    ["John", 26, "Hamilton"],
    ['Nathan', 27, "Dundas"],
    ["Lily", 19, "Halifax"],
    ["Corrin", 26, "Charlottetown"]
]

unique_id = [400130523, 400127887, 40130877, 555555555]

cols = ["Name", "Age", "City"]

df = pd.DataFrame(data = data, columns = cols, index = unique_id)

df

             Name  Age           City
400130523    John   26       Hamilton
400127887  Nathan   27         Dundas
40130877     Lily   19        Halifax
555555555  Corrin   26  Charlottetown

In [17]:
df[["Name", "Age"]]

             Name  Age
400130523    John   26
400127887  Nathan   27
40130877     Lily   19
555555555  Corrin   26

In [16]:
df["City"]

400130523         Hamilton
400127887           Dundas
40130877           Halifax
555555555    Charlottetown
Name: City, dtype: object

What if we want to see a row instead of a column?

Here we can use the `loc` method!

In [18]:
df.loc[400130523]

Name        John
Age           26
City    Hamilton
Name: 400130523, dtype: object

In [19]:
df.loc[[400130523,555555555]]

             Name  Age           City
400130523    John   26       Hamilton
555555555  Corrin   26  Charlottetown

If we don't want to use the row identifier, we can also talk about a row by its index using `iloc`.

In [20]:
df.iloc[1]

Name    Nathan
Age         27
City    Dundas
Name: 400127887, dtype: object

We can also look at a range of columns or locations, or even extract an entire sub-dataframe.

In [21]:
df[["Name", "Age"]]

             Name  Age
400130523    John   26
400127887  Nathan   27
40130877     Lily   19
555555555  Corrin   26

In [22]:
df.loc[400130523:40130877, "Name" : "Age"]

             Name  Age
400130523    John   26
400127887  Nathan   27
40130877     Lily   19

### Reading in from file

In [23]:
df = pd.read_csv('grades.csv')

In [25]:
df

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,BARRY,LAMB,620565656,96,77,82,91,88,78,91
1,NARIMAN,PELUCHONDELAGARZA,107856531,94,76,87,90,90,67,88
2,VITALY,KHAN,7943944,92,79,85,92,76,60,87
3,NATALYA,SUTRADHAR,114037001,90,75,78,88,90,67,84
4,MAGARET,HIRJI,581943811,88,76,91,98,96,56,81
...,...,...,...,...,...,...,...,...,...,...
246,JANAYA,ELZOEIBY,248015969,94,72,82,91,92,69,93
247,PATRYK,BERNIQUER,970187185,95,72,88,94,88,67,95
248,ARIANNA,DMITROVICH,300391145,91,73,84,94,96,75,83
249,CHERISE,MILEUSNIC,149614639,92,78,79,91,90,65,90
250,DUMITRU,SHAH,849296811,94,65,86,87,83,74,85

Sometimes datasets will be too large to view in one frame. The `head()` command lets us see the first 5 rows and the `tail()` command lets us see the last 5.

In [26]:
df.head()

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,BARRY,LAMB,620565656,96,77,82,91,88,78,91
1,NARIMAN,PELUCHONDELAGARZA,107856531,94,76,87,90,90,67,88
2,VITALY,KHAN,7943944,92,79,85,92,76,60,87
3,NATALYA,SUTRADHAR,114037001,90,75,78,88,90,67,84
4,MAGARET,HIRJI,581943811,88,76,91,98,96,56,81

In [27]:
df.tail()

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
246,JANAYA,ELZOEIBY,248015969,94,72,82,91,92,69,93
247,PATRYK,BERNIQUER,970187185,95,72,88,94,88,67,95
248,ARIANNA,DMITROVICH,300391145,91,73,84,94,96,75,83
249,CHERISE,MILEUSNIC,149614639,92,78,79,91,90,65,90
250,DUMITRU,SHAH,849296811,94,65,86,87,83,74,85

To gain some more insight, we can also ask for a high level description of our data.

In [28]:
df.describe()

,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
count,2.510000e+02,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000,251.000000
mean,4.984112e+08,94.426295,75.011952,84.737052,89.486056,87.418327,66.410359,86.358566
std,2.901462e+08,4.380587,5.310730,5.085133,4.767683,5.030736,5.424660,4.940336
min,3.399850e+05,81.000000,62.000000,71.000000,74.000000,75.000000,50.000000,74.000000
25%,2.615895e+08,91.000000,72.000000,81.000000,86.000000,83.500000,63.000000,83.000000
50%,4.856893e+08,94.000000,75.000000,84.000000,90.000000,88.000000,66.000000,86.000000
75%,7.586081e+08,98.000000,78.000000,88.000000,93.000000,91.000000,70.000000,90.000000
max,9.998414e+08,100.000000,89.000000,98.000000,100.000000,100.000000,78.000000,100.000000

In [34]:
df[' Quizzes average']

0      96
1      94
2      92
3      90
4      88
       ..
246    94
247    95
248    91
249    92
250    94
Name:  Quizzes average, Length: 251, dtype: int64

In [ ]:
df.columns

In [ ]:
df.loc[len(df)+1] = ["Mike", "Wazowski", 400130523, 29.9, 29.9, 29.9, 29.9, 22.2, 22.2, 30.2]

### Filtering

We can use similar Boolean syntax as in Numpy to filter through data frames and series.

In [ ]:
df[df[' Final exam mark']> 92.0]

In [ ]:
df[(df[' Final exam mark']>92.0) & (df[' Quizzes average']> 98.0)]

### Sorting

We may also sort a data frame by a column or row. Note that the data being sorted must have a well defined order. 

**Note:** We may choose specifically the sorting algorithm we wish to use. By default pandas uses quicksort.

In [ ]:
df.sort_values(' Final exam mark', ascending = False, kind = 'quicksort').head()

### Example calculation involving grades

In [ ]:
df = pd.read_csv('grades.csv')

### Final grading scheme
1. Scheme 1
- 10% Quizzes
- 20% HW
- 40% Exams (20% each)
- 30% Final Exam
2. Scheme 2
- 10% Quizzes
- 20% HW
- 20% Exams (Best 1 of 2)
- 50% Final Exam

In [ ]:
final_grade1 = 0.1*df[' Quizzes average'] + 0.2*((df[' HW1 mark']+ df[' HW2 mark']+ df[' HW3 mark'])/3) + 0.2*(df[' Exam1 mark']) + 0.2*(df[' Exam2 mark'])+0.3*(df[' Final exam mark'])

final_grade2 = 0.1*df[' Quizzes average'] + 0.2*((df[' HW1 mark']+ df[' HW2 mark']+ df[' HW3 mark'])/3) + 0.2*(df[[' Exam1 mark', ' Exam2 mark']].max(axis = 1))+0.5*(df[' Final exam mark'])

df.insert(10,'Final grade scheme 1', final_grade1)
df.insert(11, 'Final grade scheme 2', final_grade2)

In [ ]:
final_grade = df[['Final grade scheme 1', 'Final grade scheme 2']].max(axis = 1)
df.insert(12, 'Final grade', final_grade)

In [ ]:
df

### Dealing with missing data

Let's now try to accomplish the same goal as before, but this time with a more realistic data set.

In [ ]:
gradeBook = pd.read_csv('grades_missing.csv', na_values = [' '])

In [ ]:
gradeBook

We must choose how we deal with NaN values. In the case of grades, inserting zero works, but in other data sets this will not make sense. For instance, in some cases, inserting the mean of the data set is best.

In [ ]:
gradeBook = gradeBook.fillna(0)

In [ ]:
final_grade1 = 0.1*gradeBook[' Quizzes average'] + 0.2*((gradeBook[' HW1 mark']+ gradeBook[' HW2 mark']+ gradeBook[' HW3 mark'])/3) + 0.2*(gradeBook[' Exam1 mark']) + 0.2*(gradeBook[' Exam2 mark'])+0.3*(gradeBook[' Final exam mark'])

final_grade2 = 0.1*gradeBook[' Quizzes average'] + 0.2*((gradeBook[' HW1 mark']+ gradeBook[' HW2 mark']+ gradeBook[' HW3 mark'])/3) + 0.2*(gradeBook[[' Exam1 mark', ' Exam2 mark']].max(axis = 1))+0.5*(gradeBook[' Final exam mark'])

gradeBook.insert(10,'Final grade scheme 1', final_grade1)
gradeBook.insert(11, 'Final grade scheme 2', final_grade2)

In [ ]:
final_grade = gradeBook[['Final grade scheme 1', 'Final grade scheme 2']].max(axis = 1)
gradeBook.insert(12, 'Final grade', final_grade)

In [ ]:
gradeBook

Depending on the kind of data, sometimes it is best to remove all data that contains *NaN* values. For instance, when getting ethics approval for a research project involving a survey, it is sometimes required that all partially completed surveys be removed from the data set.

We can use the `dropna()` command for this.